project:
  type: website

website:
  title: "Eury's Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hongeury

format:
  html:
    theme: quartz
    css: styles.css

execute:
  freeze: auto


